= Railroad Oriented Programming in C#: Part 1

## The problem: implicit function failure

Functions are often designed for the *success path*: the return type only consists of the type the function will return in case of a successful execution.
The following function definition likely wouldn't stand out in an average code base.

[source,cs]
....
User GetUser(string username);
....

This function is supposed to return a User object for the user with the username that is passed into the function.
But sometimes the function isn't able to meet this expectation.

- maybe the user doesn't exist
- maybe because it needs to do a lookup in a datastore and the datastore is temporarily unreachable
- ...

If a function fails, usually one of the following things happens.

. A default value is returned, such as a null reference.
. An exception is thrown.


[pikchr]
....
include::rop.pikchr[]

X0: oval "username" fit
arrow
X1: box "GetUser" fit
arrow 
X2: oval "User" fill lightblue fit
down
arrow dashed from X1.s down
X3: oval "?" fill crimson fit
....

### Problems with using default values for failure
- For *value types* the default value is a valid member of the value space of the type. So there would be no way to distinguish between a success return value and a failure return value in this case.
- For *reference types* the default value (`null`) is not a valid member of the value space. The compiler however treats it as it _were_ a valid member, leading to null-reference bugs. Since the addition of nonnullable reference types in C# 8.0 this set of problems has been diminished a great deal, but a non-negligible pool of pitfalls remains.
- There is no way to return any data along with the failure, such as an error message or some object indicating the reason or nature of the failure.
- There is no way to distinghuish between different kinds of failures.

### Problems with using exceptions for failure
- Exceptions are not part of the function signature. As such a caller of a function does not know which exceptions to catch unless he reads all the code that is possibly hit by the function, assuming that he even has access to it.
- In well-defined and well-maintained APIs the list of possible exceptions a function can throw is stated in the documentation. But the compiler is not aware of this. So:
  * The user of the API can easily overlook exceptions and get away without compiler warnings.
  * If the API changes over time and adds more exceptions, the user will not be notified of this by the compiler.
  * Most functions are not part of a well-defined API.

### The problem of implicit failure in general
While the above paragraphs point out some problems with the respective failure-handling strategies, perhaps the biggest of all problems is this: the *failure path* of `GetUser` is *implicitly defined*.
It is not part of the function signature, and the compiler is not aware of it.
As such, it doesn't get the same amount of attention from the programmer as the success path and is, frankly, too often completely overlooked.

### Solution: explicit failure
The solution is pretty obvious: make the failure path part of the normal return type of the function.

[pikchr]
....
scale = 0.8
linewid = .5cm
lineht = .5cm
boxwid = 3.5cm

X0: oval "username" fit
arrow
X1: box "GetUser" fit

arrow from X1.ne right color lightblue
oval "Success" fit fill lightblue
arrow from X1.se right color orange
oval "Failure" fit fill orange
....

[source,cs]
....
(User OR Error) GetUser(string username);
....

This sounds trivial, so why isn't this done traditionally?
At least part of that has to do with the fact C-like languages do not make it easy to do this.
You would need to have a return type that can be _either_ the success type _or_ the failure type.
In functional programming languages such a construct _does_ exist and is called a https://en.wikipedia.org/wiki/Tagged_union[Discriminated Union].
But C-like languages, including C#, do not have support for such a type.
Luckily C# has had added lots of language features over the years that make it possible to emulate discriminated unions and use them in a relatively convenient and type-safe way.
We will have a look at one way of implementing explicit failure in C#: a `Result` type with two subtypes, one for the success path and one for the failure path.

### There is still a place for exceptions
Making the failure path part of the function return type does not mean that there are no exceptional situations for which the exception throwing mechanism is a good fit.
To give an extreme example, almost any function can _in theory_ encounter an `OutOfMemoryException` while doing an allocation.
Or any function could _in theory_ contain a bug causing a `NullReferenceException` to be thrown.
But this does not mean that we should write every function with that in mind, and have it be part of the normal failure path.
These cases are really exceptions which are *unexpected*, and should not happen.
There is often no proper way to handle them other than to cancel the whole "operation" and present the user with an appropriate error, indicating that something went completely sideways.

A good way for deciding whether to propagate a failure by throwing an exception is by asking the following question.
_Would the exeption be handled with no error-specific logic and should it cause the entire operation that is being done to be aborted_?
If the answer is yes, then it is probably appropriate to let the failure be handled by throwing an exception and catch it up the callchain at the "edge of the operation".

What the scope of that "operation" should be is completely context dependent.
For instance, in a web application that could be the http request. 
In other contexts, like a CLI progam, it could be the whole process. 
Again, note that the edges of the code that constitutes an "operation" should have appropriate try/catch clauses.

Tldr, exceptions should not be dealt with on a function level but rather on an "operation" level, and they are really *exceptional*.

## A Result type supporting the failure path
While C# does not directory support Discriminated Unions, it does support subclassing.
Since a class can have multiple subclasses, and any object is always just one of them, we can use this phenomenon to implement the notion of having two returntypes, one for success result, and one for the failure result.

[source,cs]
....
public abstract class Result {
  public sealed class Success : Result { }
  public sealed class Failure : Result { }
  // Private constructor so we are certain that Success and Failure are the only subclasses
  private Result () { }
}
....

However, this class does not allow us to associate any return data with either the success or the failure result.
We can fix that.

[source,cs]
....
public abstract class Result<TSuccess, TFailure> {
  public sealed class Success : Result<TSuccess, TFailure> {
    public readonly TSuccess SuccessValue;
    public Success(TSuccess result){
      SuccessValue = result;
    }
  }
  public sealed class Failure : Result<TSuccess, TFailure> {
    public readonly TFailure FailureValue;
    public Failure(TFailure error){
      FailureValue = error;
    }
  }
  // Private constructor so we are certain that Success and Failure are the only subclasses
  private Result () { }
}
....

With this in our toolkit we can now implement our `GetEmailAddress` function from earlier with an explicit failure path.

[source,cs]
....
Result<User, string> GetUser(string username) {
  var user = Datastore.FindUser(username);
  if (user == null)
    return new Result<User, string>.Failure("User has no email");
  return new Result<User, string>.Success(user);
}
....

Usage of this function would look something like

[source,cs]
....
var result = GetUser(username);
if (result is Result<User,string>.Success) {
  var user = ((Result<User,string>.Success)result).ResultValue;
  // Do what you wanna do
} else {
  var error = ((Result<User,string>.Failure)result).ErrorValue;
  // Handle the failure appropriately
}
....

As you can see we've achieved an explicit failure path.
When we call `GetUser` we obtain a result object and this encourages us to consider both the success and the failure case.
But the code leaves much to be desired.
Even more so when we need to call more than one function.

[source,cs]
....
Result<string, string> GetEmailAddress(User user);

// ...

var result = GetUser(username);
if (result is Result<User, string>.Success) {
  var email = ((Result<User, string>.Success)result).ResultValue;
  var result2 = GetEmailAddress(email);
  if (result2 is Result<string, string>.Success) {
    var message = ((Result<string, string>.Success)result2).ResultValue;
    // And so on...
  } else {
    var error2 = ((Result<string, string>.Failure)result2).ErrorValue;
    // Handle the failure appropriately
  }
} else {
  var error = ((Result<User, string>.Failure)result).ErrorValue;
  // Handle the failure appropriately
}
....

We would like to

- not have to unwrap the result type by doing a type check + cast
- not have a new nesting level for each subsequent function we call
- not have to handle all failures individually
- not have to specify the whole type when creating a Result instance: `new Result<User, string>.Success()`

## A Fluent Result type

To resolve the complaints about our previous implementation, we'll define an `OnSuccess` function and a `Handle` function.
They will do the unwrapping for us and form a https://en.wikipedia.org/wiki/Fluent_interface[Fluent Interface] and thereby removing the nesting.
Moreover, the OnSuccess function will "shortcircuit" the failure path, such that we only have to handle the failure path once.

[source,cs]
....
public abstract class Result<TS, TF> {
  public abstract Result<TNextR, TF> OnSuccess<TNextR>(Func<TS, Result<TNextR, TF>> onSuccess);
  public abstract TReturn Handle<TReturn>(Func<TS, TReturn> onSuccess, Func<TF, TReturn> onFailure);

  public sealed class Success : Result<TS, TF> {
    public TS SuccessValue { get; }

    public Success(TS result) => SuccessValue = result;

    public override Result<TNextR, TF> OnSuccess<TNextR>(Func<TS, Result<TNextR, TF>> onSuccess)
        => onSuccess(SuccessValue);

    public override TReturn Handle<TReturn>(Func<TS, TReturn> onSuccess, Func<TF, TReturn> onFailure)
        => onSuccess(SuccessValue);
  }

  public sealed class Failure : Result<TS, TF> {
    public TF FailureValue { get; }

    public Failure(TF error) => FailureValue = error;

    public override Result<TNextR, TF> OnSuccess<TNextR>(Func<TS, Result<TNextR, TF>> onSuccess)
        => Result.Fail(FailureValue);

    public override TReturn Handle<TReturn>(Func<TS, TReturn> onSuccess, Func<TF, TReturn> onFailure)
        => onFailure(FailureValue);
  }

  private Result() { }
}
....

Apart from the daunting function signatures, the actual function bodies are trivial.
Yet they suddenly allow us to write very concise code.
Compare the following with what we had in the previous section.

[source,cs]
....
GetUser(username)
  .OnSuccess(GetEmailAddress);
  .Handle(
    emailAddress => ..., // Do your thing
    error => ... // Handle the failure appropriately
  );
....

This style of programming is sometimes referred to as https://fsharpforfunandprofit.com/rop/[_railway oriented programming_], a term first invented by Scott Wlaschin.
Why that is the case is easily demonstrated with some diagrams.
The Result type encapsulates two "paths" or "tracks", the success track and the failure track.

[pikchr]
....
scale = .8

R: oval "Result" fit
arrow from R.n right color lightblue behind R
oval "Success" fit fill lightblue
arrow from R.s right color orange behind R
oval "Failure" fit fill orange
....

And the `OnSuccess` and `Handle` methods form trackpieces.

[pikchr]
....
include::rop.pikchr[]

onSuccess("OnSuccess")
move right
handle("Handle")
....

The railway of the example code would look like

[pikchr]
....
include::rop.pikchr[]

onSuccess("GetUser")
onSuccess("GetEmailAddress")
handle("Handle")
oval "message" fit
....

### Another Example

Suppose now that we needed to write the following function.

[source,cs]
....
/// <returns>Message to be printed on the screen</returns>
string MailMessageToUser(string username, string msg);
....

And suppose that we have the following functions at our disposal.

[source,cs]
....
Result<User, string> GetUser(string username);
Result<string, string> GetEmailAddress(User user);
Result<EmailMessage, string> CreateEmailMessage(string emailAddress, string msg);
Result<Unit, string> SendEmail(EmailMessage email);
....

Then we could implement the function as follows.

[source,cs]
....
/// <returns>Message to be printed on the screen</returns>
string MailMessageToUser(string username, string msg) {
  return GetUser(username)
    .OnSuccess(GetEmailAddress)
    .OnSuccess(email => CreateEmailMessage(email, msg))
    .OnSuccess(SendEmail)
    .Handle(
      _ => "Email sent",
      error => {
        Log(error);
        return "Email not sent";
      }
    );
}
....

The railway of the example code would look like

[pikchr]
....
include::rop.pikchr[]

onSuccess("GetUser")
onSuccess("GetEmailAddress")
onSuccess("CreateEmailMessage")
onSuccess("SendEmail")
handle("Handle")
oval "message" fit
....

### The OnFailure method

If we have a OnSuccess method, there is no reason why we couldn't have an OnFailure method too.
This would allow us to do operations on the failure track, such as modifying or logging the error, or recovering from the error and get back on the success track.

[pikchr]
....
include::rop.pikchr[]

onFailure("OnFailure")
....

[source,cs]
....
/// <returns>Message to be printed on the screen</returns>
string MailMessageToUser(string username, string msg) {
  return GetUser(username)
    .OnSuccess(GetEmailAddress)
    .OnSuccess(email => CreateEmailMessage(email, msg))
    .OnSuccess(SendEmail)
    .OnFailure(Log)
    .Handle(
      _ => "Email sent",
      _ => "Email not sent"
    );
}
....

[pikchr]
....
include::rop.pikchr[]

onSuccess("GetUser")
onSuccess("GetEmailAddress")
onSuccess("CreateEmailMessage")
onSuccess("SendEmail")
onFailureF("LogFailure")
handle("Handle")
oval "message" fit
....

### Sub tracks

[source,cs]
....
/// <returns>Message to be printed on the screen</returns>
string MailMessageToUser(string username, string msg) {
  MailServerConfig server1 = new();
  MailServerConfig server2 = new();
  return GetUser(username)
    .OnSuccess(GetEmailAddress)
    .OnSuccess(emailAddress => CreateEmailMessage(emailAddress, msg))
    .OnSuccess(email => SendEmail(email, server1)
      .OnFailure(ex => ex switch {
        ServerNotFoundException =>
          SendEmail(email, server2).OnFailure(ex => new Result<Unit, string>.Failure(ex.Message)),
        _ => new Result<Unit, string>.Failure(ex.Message)
      })
    )
    .OnFailure(Log)
    .Handle(
      _ => "Email sent",
      _ => "Email not sent"
    );
}
....

[pikchr]
....
include::rop.pikchr[]

linewid = .1

onSuccess("GetUser")
onSuccess("GetEmailAddress")
onSuccess("CreateEmailMessage")

S0: arrow color lightblue
B1: box "SendEmail" fit
arrow right linewid*3 color orange behind B1
B2: box "SendEmail2" fit
E: line right linewid*3 color lightblue behind B2

line from B1.e right linerad then down then right color orange behind B1

move from S0.start down lineht
line right until even with E.end color orange

line from B1.e right linerad then down then right color orange behind B1
line from B2.e right linerad then down then right color orange behind B2

line from B1.e right linerad then up then right until even with B2.e then right linerad*2 then down then right color lightblue

onFailureF("LogFailure")
handle("Handle")
oval "message" fit
....

## Conclusion

We still need to deal with the awkward construction of Result instances, and we'll do that in the next part.
